---
-
  hosts: all
  gather_facts: true # this will make not to gather facts before running tasks

  tasks: 
   - name: Remove a service
      win_service:
       name: bits
       state: stopped
        
...